package main

import (
	"log"
	"os"

	loads "github.com/go-openapi/loads"
	flags "github.com/jessevdk/go-flags"

	"keployswagger/restapi"
	"keployswagger/restapi/operations"
)

// This file was generated by the swagger tool.
// Make sure not to overwrite this file after you generated it because all your edits would be lost!

func main() {

	swaggerSpec, err := loads.Analyzed(restapi.SwaggerJSON, "")
	if err != nil {
		log.Fatalln(err)
	}

	api := operations.NewFileUploadAPI(swaggerSpec)
	server := restapi.NewServer(api)
	server.Port = 8089
	defer server.Shutdown()

	parser := flags.NewParser(server, flags.Default)
	parser.ShortDescription = "File Upload"
	parser.LongDescription = "Example server uploading a file"

	server.ConfigureFlags()
	for _, optsGroup := range api.CommandLineOptionsGroups {
		_, err := parser.AddGroup(optsGroup.ShortDescription, optsGroup.LongDescription, optsGroup.Options)
		if err != nil {
			log.Fatalln(err)
		}
	}

	if _, err := parser.Parse(); err != nil {
		code := 1
		if fe, ok := err.(*flags.Error); ok {
			if fe.Type == flags.ErrHelp {
				code = 0
			}
		}
		os.Exit(code)
	}

	server.ConfigureAPI()

	if err := server.Serve(); err != nil {
		log.Fatalln(err)
	}

}

//ctx := params.HTTPRequest.Context()
//req, err := http.NewRequestWithContext(ctx, "GET", "google.com", nil)
//if err != nil {
//	logrus.Fatal(err)
//}
//resp, err := http.DefaultClient.Do(req)
//if err != nil {
//	logrus.Fatal(err)
//}
//defer resp.Body.Close()
//respBodyBytes, err := io.ReadAll(resp.Body)
//if err != nil {
//	logrus.Fatal(err)
//}
//logrus.Info(string(respBodyBytes))
//return middleware.NotImplemented("operation uploads.UploadFile has not yet been implemented")
